#!/usr/bin/env bash
([ -f "$(dirname $0)/.helpers" ] || curl -o "$(dirname $0)/.helpers" -L https://git.io/vrHQm) \
  && . "$(dirname $0)/.helpers"

cd $(dirname $0)/..

./script/update

title "Running test suite..."

bats test
